DIMENSIONS = ["Communication","Creativity","Independence","Income","Stability",
              "Flexibility","Analytical","Leadership","Technical","Empathy"]

# Keywords used to read signal out of the free-text answers
SKILL_KEYWORDS = {
    "Communication": ["explain","talk","writing","write","present","communicat","persua","teach","speak"],
    "Creativity":     ["creativ","design","art","idea","imagin","brainstorm","innovat"],
    "Analytical":     ["analy","data","numbers","logic","problem solv","research","detail"],
    "Leadership":     ["lead","manage","mentor","organiz team","motivat","delegat"],
    "Technical":      ["code","technical","software","build","engineer","fix","system","tool"],
    "Empathy":        ["listen","empath","care","support","help people","calm","patient"],
}

# Short, generic "why this is a strength" line per dimension — used on the Strengths page
DIMENSION_BLURB = {
    "Communication": "You explain things in ways that land with different audiences — a strength that transfers across nearly every strategic role.",
    "Creativity":     "You gravitate toward original solutions rather than the first available one.",
    "Independence":   "You do your best work with real autonomy, needing little oversight to move forward.",
    "Income":         "Financial upside is a real driver for you, not just a nice-to-have.",
    "Stability":      "You value predictability and a steady, well-defined path.",
    "Flexibility":    "You adapt easily when priorities, tools, or environments shift.",
    "Analytical":     "You default to breaking problems into pieces before acting on them.",
    "Leadership":     "You naturally take ownership and bring others along with you.",
    "Technical":      "You're comfortable going deep into tools and systems most people avoid.",
    "Empathy":        "You read people well and adjust your approach accordingly.",
}

# Short noun-phrase per dimension, used to build the one-line "next move" callout
DIMENSION_PHRASE = {
    "Communication": "clear communication",
    "Creativity":     "creative thinking",
    "Independence":   "independent execution",
    "Income":         "financial upside",
    "Stability":      "steady structure",
    "Flexibility":    "adaptability",
    "Analytical":     "analytical rigor",
    "Leadership":     "leadership",
    "Technical":      "technical depth",
    "Empathy":        "empathy",
}

CAREERS = [
    {"name":"UX Designer","v":{"Communication":7,"Creativity":9,"Independence":8,"Income":8,"Stability":6,"Flexibility":7,"Analytical":7,"Leadership":4,"Technical":6,"Empathy":6},
     "uses":["Research","Problem solving","Visual thinking","Communication"],
     "challenges":["A portfolio is expected before most employers will interview you","Entry-level roles are competitive","Requires continuous tool learning (Figma, prototyping)"],
     "build_next":["Figma (interface design)","Portfolio case studies","UX research methods","Basic prototyping"]},
    {"name":"Product Marketing Manager","v":{"Communication":9,"Creativity":7,"Independence":5,"Income":8,"Stability":6,"Flexibility":6,"Analytical":7,"Leadership":6,"Technical":4,"Empathy":6},
     "uses":["Storytelling","Strategic planning","Cross-team communication"],
     "challenges":["Success depends on other teams' execution","Fast-paced, frequent context switching","Metrics-driven accountability"],
     "build_next":["Positioning & messaging frameworks","Cross-functional stakeholder management","Basic market research methods"]},
    {"name":"Project Manager","v":{"Communication":9,"Creativity":6,"Independence":5,"Income":7,"Stability":7,"Flexibility":5,"Analytical":6,"Leadership":8,"Technical":5,"Empathy":6},
     "uses":["Organization","Communication","Stakeholder management","Planning"],
     "challenges":["Accountable for outcomes you don't fully control","Can involve constant context-switching","Certifications (PMP, Scrum) help but take time"],
     "build_next":["Project planning tools (Asana, Jira)","Agile/Scrum fundamentals","Budget & timeline management"]},
    {"name":"Content Strategist","v":{"Communication":9,"Creativity":9,"Independence":8,"Income":6,"Stability":5,"Flexibility":8,"Analytical":8,"Leadership":5,"Technical":4,"Empathy":5},
     "uses":["Writing","Research","Editorial judgment","Communication"],
     "challenges":["Income varies widely by industry and seniority","Requires a visible portfolio or writing samples","AI tools are reshaping entry-level demand"],
     "build_next":["A public writing portfolio","SEO & content research basics","Editorial style and voice development"]},
    {"name":"Data Analyst","v":{"Communication":5,"Creativity":4,"Independence":7,"Income":8,"Stability":8,"Flexibility":5,"Analytical":10,"Leadership":3,"Technical":9,"Empathy":3},
     "uses":["Analytical thinking","Technical tools (SQL, Excel)","Attention to detail"],
     "challenges":["Technical skills need active upkeep","Can be repetitive without a growth path","Communicating findings to non-technical people is a separate skill"],
     "build_next":["SQL and spreadsheet fluency","A data visualization tool (Tableau/PowerBI)","One applied analytics project"]},
    {"name":"Software Engineer","v":{"Communication":4,"Creativity":6,"Independence":8,"Income":9,"Stability":8,"Flexibility":6,"Analytical":9,"Leadership":4,"Technical":10,"Empathy":3},
     "uses":["Logical problem solving","Technical depth","Independent focus work"],
     "challenges":["Steep initial learning curve","Field changes quickly, ongoing learning required","Interview processes are demanding"],
     "build_next":["One programming language, in depth","A public GitHub portfolio","Data structures & algorithms basics"]},
    {"name":"Sales / Business Development","v":{"Communication":10,"Creativity":5,"Independence":7,"Income":9,"Stability":4,"Flexibility":6,"Analytical":5,"Leadership":6,"Technical":3,"Empathy":7},
     "uses":["Persuasion","Relationship building","Resilience"],
     "challenges":["Income can be commission-based and inconsistent","Rejection is frequent","Targets create ongoing pressure"],
     "build_next":["A CRM tool (e.g. HubSpot)","Cold outreach & pipeline basics","Negotiation fundamentals"]},
    {"name":"HR / People Partner","v":{"Communication":9,"Creativity":4,"Independence":4,"Income":5,"Stability":7,"Flexibility":5,"Analytical":5,"Leadership":7,"Technical":3,"Empathy":10},
     "uses":["Empathy","Conflict resolution","Organizational judgment"],
     "challenges":["Often mediates difficult situations","Compensation can lag other business functions","Requires emotional resilience"],
     "build_next":["Employment law basics","Conflict mediation skills","An HRIS platform"]},
    {"name":"Marketing Specialist","v":{"Communication":8,"Creativity":8,"Independence":6,"Income":7,"Stability":5,"Flexibility":7,"Analytical":7,"Leadership":5,"Technical":5,"Empathy":6},
     "uses":["Creative thinking","Communication","Data-informed decisions"],
     "challenges":["Channels and tools shift constantly","Results can be hard to attribute","Fast pace, tight deadlines"],
     "build_next":["A digital ads platform (Meta/Google)","Basic analytics reading","Campaign planning"]},
    {"name":"Entrepreneur / Founder","v":{"Communication":8,"Creativity":9,"Independence":10,"Income":6,"Stability":2,"Flexibility":9,"Analytical":6,"Leadership":9,"Technical":5,"Empathy":6},
     "uses":["Full ownership","Creative and strategic thinking","Resilience"],
     "challenges":["Income is unpredictable, especially early on","Very low structural stability","Requires wearing many hats at once"],
     "build_next":["A validated first offer","Basic financial planning","A small early customer base"]},
    {"name":"Teacher / Trainer","v":{"Communication":9,"Creativity":6,"Independence":5,"Income":3,"Stability":8,"Flexibility":4,"Analytical":5,"Leadership":6,"Technical":3,"Empathy":9},
     "uses":["Communication","Patience","Subject expertise"],
     "challenges":["Compensation is typically modest","Emotionally demanding at times","Structured schedule, less flexibility"],
     "build_next":["A teaching credential or certificate","Curriculum design basics","Classroom / cohort management"]},
    {"name":"Finance / Accounting","v":{"Communication":5,"Creativity":3,"Independence":6,"Income":8,"Stability":9,"Flexibility":3,"Analytical":9,"Leadership":4,"Technical":6,"Empathy":3},
     "uses":["Precision","Analytical rigor","Structured thinking"],
     "challenges":["Detail-heavy, low tolerance for error","Can be repetitive","Credentialing (CPA etc.) takes time"],
     "build_next":["Excel / financial modeling","Core accounting principles","A relevant certification path"]},
    {"name":"Operations Manager","v":{"Communication":7,"Creativity":4,"Independence":5,"Income":7,"Stability":8,"Flexibility":4,"Analytical":7,"Leadership":8,"Technical":5,"Empathy":5},
     "uses":["Systems thinking","Leadership","Process design"],
     "challenges":["Accountable when things go wrong across teams","Can be reactive and fast-paced","Requires cross-functional influence without full authority"],
     "build_next":["Process mapping","A project/ops tool (Notion, Asana)","Cross-team communication habits"]},
    {"name":"Graphic Designer","v":{"Communication":5,"Creativity":10,"Independence":8,"Income":5,"Stability":4,"Flexibility":8,"Analytical":5,"Leadership":3,"Technical":6,"Empathy":4},
     "uses":["Visual craft","Creative range","Independent execution"],
     "challenges":["Freelance income can be inconsistent","Client feedback cycles can be draining","Market is saturated at entry level"],
     "build_next":["A focused visual portfolio","Adobe or Figma fluency","A defined visual style / niche"]},
    {"name":"Customer Success Manager","v":{"Communication":9,"Creativity":4,"Independence":5,"Income":5,"Stability":6,"Flexibility":5,"Analytical":5,"Leadership":5,"Technical":4,"Empathy":9},
     "uses":["Empathy","Communication","Problem resolution"],
     "challenges":["Handles frustrated customers regularly","Metrics-driven, retention pressure","Can feel reactive rather than proactive"],
     "build_next":["A CRM / support tool","De-escalation techniques","Onboarding & retention basics"]},
    {"name":"Consultant","v":{"Communication":9,"Creativity":6,"Independence":7,"Income":9,"Stability":4,"Flexibility":6,"Analytical":8,"Leadership":7,"Technical":5,"Empathy":6},
     "uses":["Analytical thinking","Communication","Adaptability across industries"],
     "challenges":["Travel and long hours are common","Work is project-based, less predictable","Requires constant re-learning of new domains"],
     "build_next":["A structured problem-solving framework","Client-facing presentation skills","One deep industry specialty"]},
]
